insert into products (product, price, description, origin_country) VALUES ('Hamburger', 1.99, 'Double bacon and cheese', 'USA');
insert into products (product, price, description, origin_country) VALUES ('Pizza', 9.99, '50cm diameter', 'Italy');
insert into products (product, price, description, origin_country) VALUES ('Hot Dog', 3.99, 'Bread with linseed', 'USA');
insert into products (product, price, description, origin_country) VALUES ('French Fries', 9.99, 'Made from potatoes grown without chemicals', 'France');
insert into products (product, price, description, origin_country) VALUES ('Donut', 1.99, 'Chocolate iced and filled with creme', 'USA');
insert into products (product, price, description, origin_country) VALUES ('Cola', 1.99, 'Soft drink', 'USA');
insert into products (product, price, description, origin_country) VALUES ('Fanta', 1.99, 'Orange soft drink', 'USA');
insert into products (product, price, description, origin_country) VALUES ('Nachos', 2.99, 'Tortilla chips covered with melted cheese', 'Mexico');
insert into products (product, price, description, origin_country) VALUES ('Taco', 3.99, 'Beef and chicken meat mixed', 'Mexico');
insert into products (product, price, description, origin_country) VALUES ('Potato Chips', 1.99, 'Homemade with salt taste', 'New England');